ESPAdmin/Models/Audits.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ESPAdmin.Models
{
    public class Audits
    {
        public string ID { get; set; }
        public string TABLE_NAME { get; set; }
        public string COLUMN_NAME { get; set; }
        public string OLD_VALUE { get; set; }
        public string NEW_VALUE { get; set; }
        public string RECORD_ID { get; set; }
        public string OLD_VALUE2 { get; set; }
        public string NEW_VALUE2 { get; set; }
        public string RECORD_ID2 { get; set; }
        public string RECORD_COLUMN { get; set; }
        public string CHANGED_BY { get; set; }
        public string DATE_CHANGED { get; set; }
        public string APPROVED_BY { get; set; }
        public string DATE_APPROVED { get; set; }
        public string STATUS { get; set; }
        public string CHANGE_TYPE { get; set; }
        public string COLUMN_TYPE { get; set; }
        public string RECORD_COLUMN_TYPE { get; set; }
        public string NOTE { get; set; }
    }
}

ESPAdmin/Models/ExternalUsers.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ESPAdmin.Models
{
    public class ExternalUsers
    {
        public string ID { get; set; }
        public string PHONE { get; set; }
        public string FULLNAME { get; set; }
        public string EMAIL { get; set; }
        public string LOCKED { get; set; }
        public string STATUS { get; set; }
        public string ROLE_ID { get; set; }
        public string PCODE { get; set; }
        public string CompanyName { get; set; }
        public string DATE_LAST_MODIFIED { get; set; }
    }
}

ESPAdmin/Controllers/EmployersController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;
using ESPAdmin.Models;
using DataTables.Mvc;
using ESPAdmin.Utility;

namespace ESPAdmin.Controllers
{
    public class EmployersController : Controller
    {
        protected void Application_BeginRequest(object sender, EventArgs e)
        {
            var application = sender as HttpApplication;
            if (application != null && application.Context != null)
            {
                application.Context.Response.Headers.Remove("Server");
            }

            Response.AddHeader("x-frame-options", "DENY");
        }

        // GET: Employer
        [System.Xml.Serialization.XmlInclude(typeof(Object[]))]

        [Authorize]
        public ActionResult Index()
        {
            if (TempData["message"] != null)
            {
                ViewBag.Message = TempData["message"].ToString();
            }
            if (TempData["smessage"] != null)
            {
                ViewBag.sMessage = TempData["smessage"].ToString();
            }
            return View();
        }

        [Authorize]
        public JsonResult GetEmployers([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel)
        {
            
            string userkey = ConfigurationManager.AppSettings["userkey"];
            string uid = ConfigurationManager.AppSettings["uid"];
            string LoginUser = (string)Session["LoginSAPID"];
            string RoleID = (string)Session["RoleID"];
            string WebUserID = (string)Session["WebUserID"];

            try
            {
                
                if (RoleID == "1") {
                    Employer.Employer employer = new Employer.Employer();
                    DataTable dt = employer.FetchCompanies("YES", LoginUser);
                    dt.TableName = "Employer";

                    List<Employers> employerList = new List<Employers>();
                    int startRec = requestModel.Start;
                    int pageSize = requestModel.Length;


                    List<Employers> employerCount = (from DataRow dr in dt.Rows
                                                     select new Employers()
                                                     {
                                                         EmployerID = dr["EmployerID"].ToString(),
                                                         CompanyName = dr["Company Name"].ToString(),
                                                     }).ToList();

                    employerList = (from DataRow dr in dt.Rows
                                    select new Employers()
                                    {
                                        EmployerID = dr["EmployerID"].ToString(),
                                        CompanyName = dr["Company Name"].ToString(),
                                        Address1 = dr["Address1"].ToString(),
                                        Address2 = dr["Address2"].ToString(),
                                        State = dr["State"].ToString(),
                                        Email = dr["Email"].ToString(),
                                        RelationshipManager = dr["Relationship Manager"].ToString(),
                                        RMName = dr["RM Name"].ToString()
                                    }).Skip(startRec).Take(pageSize).ToList();

                    var totalCount = employerCount.Count();
                    var filteredCount = employerList.Count();

                    if (requestModel.Search.Value != string.Empty)
                    {
                        var value = requestModel.Search.Value.ToLower().Trim();

                        employerCount = (from DataRow dr in dt.Rows
                                         where dr["EmployerID"].ToString().ToLower().Contains(value) || dr["Company Name"].ToString().ToLower().Contains(value)
                                            || dr["Email"].ToString().ToLower().Contains(value) || dr["Relationship Manager"].ToString().ToLower().Contains(value)
                                            || dr["RM Name"].ToString().ToLower().Contains(value)
                                         select new Employers()
                                         {
                                             EmployerID = dr["EmployerID"].ToString(),
                                             CompanyName = dr["Company Name"].ToString(),
                                         }).ToList();

                        employerList = (from DataRow dr in dt.Rows
                                        where dr["EmployerID"].ToString().ToLower().Contains(value) || dr["Company Name"].ToString().ToLower().Contains(value)
                                            || dr["Email"].ToString().ToLower().Contains(value) || dr["Relationship Manager"].ToString().ToLower().Contains(value)
                                            || dr["RM Name"].ToString().ToLower().Contains(value)
                                        select new Employers()
                                        {
                                            EmployerID = dr["EmployerID"].ToString(),
                                            CompanyName = dr["Company Name"].ToString(),
                                            Address1 = dr["Address1"].ToString(),
                                            Address2 = dr["Address2"].ToString(),
                                            State = dr["State"].ToString(),
                                            Email = dr["Email"].ToString(),
                                            RelationshipManager = dr["Relationship Manager"].ToString(),
                                            RMName = dr["RM Name"].ToString()
                                        }).Skip(startRec).Take(pageSize).ToList();

                        totalCount = employerCount.Count();
                        filteredCount = employerList.Count();

                    }

                    var sortedColumns = requestModel.Columns.GetSortedColumns();
                    var orderByString = String.Empty;

                    foreach (var column in sortedColumns)
                    {
                        orderByString += orderByString != String.Empty ? "," : "";
                        orderByString += (column.Data) + (column.SortDirection == Column.OrderDirection.Ascendant ? " asc" : " desc");
                    }

                    var data = employerList.Select(emList => new
                    {
                        EmployerID = emList.EmployerID,
                        CompanyName = emList.CompanyName,
                        Address1 = emList.Address1,
                        Address2 = emList.Address2,
                        State = emList.State,
                        Email = emList.Email,
                        RelationshipManager = emList.RelationshipManager,
                        RMName = emList.RMName
                    }).OrderBy(orderByString == string.Empty ? "EmployerID asc" : orderByString).ToList();

                    return Json(new DataTablesResponse(requestModel.Draw, data, totalCount, totalCount), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    Employer.Employer employer = new Employer.Employer();
                    DataTable dt = employer.FetchCompanies("All", "");
                    dt.TableName = "Employer";

                    List<Employers> employerList = new List<Employers>();
                    int startRec = requestModel.Start;
                    int pageSize = requestModel.Length;


                    List<Employers> employerCount = (from DataRow dr in dt.Rows
                                                     select new Employers()
                                                     {
                                                         EmployerID = dr["EmployerID"].ToString(),
                                                         CompanyName = dr["Company Name"].ToString(),
                                                     }).ToList();

                    employerList = (from DataRow dr in dt.Rows
                                    select new Employers()
                                    {
                                        EmployerID = dr["EmployerID"].ToString(),
                                        CompanyName = dr["Company Name"].ToString(),
                                        Address1 = dr["Address1"].ToString(),
                                        Address2 = dr["Address2"].ToString(),
                                        State = dr["State"].ToString(),
                                        Email = dr["Email"].ToString(),
                                        RelationshipManager = dr["Relationship Manager"].ToString(),
                                        RMName = dr["RM Name"].ToString()
                                    }).Skip(startRec).Take(pageSize).ToList();

                    var totalCount = employerCount.Count();
                    var filteredCount = employerList.Count();

                    if (requestModel.Search.Value != string.Empty)
                    {
                        var value = requestModel.Search.Value.ToLower().Trim();

                        employerCount = (from DataRow dr in dt.Rows
                                         where dr["EmployerID"].ToString().ToLower().Contains(value) || dr["Company Name"].ToString().ToLower().Contains(value)
                                            || dr["Email"].ToString().ToLower().Contains(value) || dr["Relationship Manager"].ToString().ToLower().Contains(value)
                                            || dr["RM Name"].ToString().ToLower().Contains(value)
                                         select new Employers()

ESPAdmin/Views/Admin/Audits.cshtml
@{
    ViewBag.Title = "Index";
}

<link href="~/Content/jquery-confirm.min.css" rel="stylesheet" />
<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title ">
                    Admin
                </h3>
                <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                    <li class="m-nav__item m-nav__item--home">
                        <a href="#" class="m-nav__link m-nav__link--icon">
                            <i class="m-nav__link-icon la la-home"></i>
                        </a>
                    </li>
                    <li class="m-nav__separator">
                        -
                    </li>
                    <li class="m-nav__item">
                        <a href="" class="m-nav__link">
                            <span class="m-nav__link-text">
                                Actions
                            </span>
                        </a>
                    </li>
                    <li class="m-nav__separator">
                        -
                    </li>
                    <li class="m-nav__item">
                        <a href="" class="m-nav__link">
                            <span class="m-nav__link-text">
                                Admin Users List
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="m-content">
        @if (ViewBag.Message != null)
        {
            <div class="m-alert m-alert--icon m-alert--icon-solid m-alert--outline alert alert-danger alert-dismissible fade show m--margin-bottom-30" role="alert">
                <div class="m-alert__icon">
                    <i class="flaticon-exclamation-1"></i>
                    <span></span>
                </div>
                <div class="m-alert__text">
                    @ViewBag.Message
                </div>
                <div class="m-alert__close">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        }

        @if (ViewBag.sMessage != null)
        {
            <div class="m-alert m-alert--icon m-alert--icon-solid m-alert--outline alert alert-brand alert-dismissible fade show m--margin-bottom-30" role="alert">
                <div class="m-alert__icon">
                    <i class="flaticon-exclamation-1"></i>
                    <span></span>
                </div>
                <div class="m-alert__text">
                    @ViewBag.sMessage
                </div>
                <div class="m-alert__close">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        }
        
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Admin Users List
                        </h3>
                    </div>
                    
                </div>
            </div>

            <div class="m-portlet__body">
                <!--begin: Datatable -->
                <div class="m_datatable m-datatable m-datatable--default m-datatable--loaded">
                    <table id="employer-data-table" class="datatable__table table table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>TABLE NAME</th>
                                <th>COLUMN NAME</th>
                                <th>CHANGED BY</th>
                                <th>APPROVED BY</th>
                                <th>NOTE</th>
                                <th>DATE CHANGED</th>
                                <th>DATE APPROVED</th>
                            </tr>
                        </thead>
                    </table>
                </div>
                <!--end: Datatable -->
            </div>
        </div>
    </div>

</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

<script type="text/javascript">
    var assetListVM;
        $(function () {
            assetListVM = {
                dt: null,
                init: function () {
                    dt = $('#employer-data-table').DataTable({
                        "serverSide": true,
                        "processing": true,
                        "stateSave": true,
                        "ajax": {
                            "url": "@Url.Action("GetAudits", "Admin")"
                        },
                        "columns": [
                            {"data": "ID"},
                            {"data": "TABLE_NAME"},
                            {"data": "COLUMN_NAME" },
                            {"data": "CHANGED_BY"},
                            {"data": "APPROVED_BY"},
                            {"data": "NOTE"},
                            {"data": "DATE_CHANGED"},
                            {"data": "DATE_APPROVED"}
                        ],
                        "aoColumns": [
                            {"mData": "ID", sDefaultContent: ""},
                            {"mData": "TABLE_NAME", sDefaultContent: ""},
                            {"mData": "COLUMN_NAME", sDefaultContent: ""},
                            {"mData": "CHANGED_BY", sDefaultContent: ""},
                            {"mData": "APPROVED_BY", sDefaultContent: ""},
                            {"mData": "NOTE", sDefaultContent: ""},
                            {"mData": "DATE_CHANGED", sDefaultContent: ""},
                            {"mData": "DATE_APPROVED", sDefaultContent: ""},
                        ],
                        responsive: {
                           details: {
                               display: $.fn.dataTable.Responsive.display.modal({
                                   header: function ( row ) {
                                       var data = row.data();
                                       return 'Audit Details';
                                   }
                               }),
                               renderer: $.fn.dataTable.Responsive.renderer.tableAll({
                                   tableClass: 'table'
                               })
                           }
                       },
                       "lengthMenu": [[10, 25, 50, 100], [10, 25, 50, 100]],
                    });
                }
            }
            // initialize the datatables
            assetListVM.init();
        });
    </script>

ESPAdmin/Views/Admin/CreateEmployerContact.cshtml
@{
    ViewBag.Title = "CreateEmployerContact";
}

<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title ">
                    New Employer Contact
                </h3>
                <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                    <li class="m-nav__item m-nav__item--home">
                        <a href="#" class="m-nav__link m-nav__link--icon">
                            <i class="m-nav__link-icon la la-home"></i>
                        </a>
                    </li>
                    <li class="m-nav__separator">
                        -
                    </li>
                    <li class="m-nav__item">
                        <a href="" class="m-nav__link">
                            <span class="m-nav__link-text">
                                Actions
                            </span>
                        </a>
                    </li>
                    <li class="m-nav__separator">
                        -
                    </li>
                    <li class="m-nav__item">
                        <a href="" class="m-nav__link">
                            <span class="m-nav__link-text">
                                New Contact
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="m-content">
        <div class="row">
            <div class="col-lg-6">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide">
                                    <i class="la la-gear"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    New Employer Contact
                                </h3>
                            </div>
                        </div>
                    </div>
                    <!--begin::Form-->
                    
                    <form class="m-form m-form--fit" method="post" action="@Url.Action("CreateEmployerContact","Employers")">
                        @Html.AntiForgeryToken()
                        <div class="m-portlet__body">
                            <div class="m-form__section m-form__section--first">
                                <div class="m-form__heading">
                                    @if (ViewBag.Error != null)
                                    {
                                        <alert class="alert alert-danger">@ViewBag.Error</alert>
                                    }
                                </div>
                                <div class="m-form__heading">
                                    <h3 class="m-form__heading-title">User Info.</h3>
                                </div>
                                <div class="form-group m-form__group">
                                    <div class="ui-widget">
                                        <label for="example_input_full_name">Employer ID:</label>
                                        <input type="text" name="EmployerId" class="form-control m-input" placeholder="Please Select The Employer" id="employerList" required>
                                        <span class="m-form__help">Please enter the first 2 digit of the employer name to get the Employer ID</span>
                                    </div>
                                </div>
                                <div class="form-group m-form__group">
                                    <label for="example_input_full_name">Fullname:</label>
                                    <input type="text" name="Fullname" class="form-control m-input" placeholder="Enter Contact Fullname" required>
                                </div>
                                <div class="form-group m-form__group">
                                    <label for="example_input_full_name">Email Address:</label>
                                    <input type="text" name="Email" class="form-control m-input" placeholder="Enter Contact Email Address" required>
                                </div>
                                <div class="form-group m-form__group">
                                    <label for="example_input_full_name">Phone Number:</label>
                                    <input type="text" name="PhoneNo" class="form-control m-input" placeholder="Enter Contact Phone Number" required>
                                </div>
                                <div class="form-group m-form__group">
                                    <label>Role:</label>
                                    <select name="Role" class="form-control m-input" id="roles" required>
                                        <option value="">Select A Role</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                            <div class="m-form__actions m-form__actions--solid">
                                <button type="submit" class="btn btn-success">Submit</button>
                                <button type="reset" class="btn btn-secondary">Cancel</button>
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
                <!--end::Portlet-->
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

<script type="text/javascript">
    $("#employerList").autocomplete({
        source: function(request,response) {
            $.ajax({
                url: "@Url.Action("GetEmployersList", "Admin")",
                type: "POST",
                dataType: "json",
                data: { Prefix: request.term },
                success: function (data) {
                    response($.map(data.data, function (item) {
                        $("#employerList").removeClass( "ui-autocomplete-loading" );
                        return { label: item.CompanyName, value: item.EmployerID};
                    }));
                }
            })
        },
        minLength: 2,
        messages: {
            noResults: "", results: ""
        },
    });
</script>

ESPAdmin/Views/Admin/CreateRole.cshtml
@{
    ViewBag.Title = "ViewStaffs";
}

<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title ">
                    New Role
                </h3>
                <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                    <li class="m-nav__item m-nav__item--home">
                        <a href="#" class="m-nav__link m-nav__link--icon">
                            <i class="m-nav__link-icon la la-home"></i>
                        </a>
                    </li>
                    <li class="m-nav__separator">
                        -
                    </li>
                    <li class="m-nav__item">
                        <a href="" class="m-nav__link">
                            <span class="m-nav__link-text">
                                Actions
                            </span>
                        </a>
                    </li>
                    <li class="m-nav__separator">
                        -
                    </li>
                    <li class="m-nav__item">
                        <a href="" class="m-nav__link">
                            <span class="m-nav__link-text">
                                New Role
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="m-content">
        <div class="row">
            <div class="col-lg-6">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide">
                                    <i class="la la-gear"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    New Role
                                </h3>
                            </div>
                        </div>
                    </div>
                    <!--begin::Form-->
                    
                    <form class="m-form m-form--fit" method="post" action="@Url.Action("CreateRole", "Admin")">
                        @Html.AntiForgeryToken()
                        <div class="m-portlet__body">
                            <div class="m-form__section m-form__section--first">
                                <div class="m-form__heading">
                                    @if (ViewBag.Error != null)
                                    {
                                        <alert class="alert alert-danger">@ViewBag.Error</alert>
                                    }
                                </div>
                                <div class="m-form__heading">
                                    <h3 class="m-form__heading-title">Role Info:</h3>
                                </div>
                                <div class="form-group m-form__group">
                                    <label for="example_input_full_name">Name:</label>
                                    <input type="text" name="Name" class="form-control m-input" placeholder="Enter Name of Role" required>
                                    <span class="m-form__help">Please Enter Name of Role</span>
                                </div>
                            </div>
                        </div>
                        <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                            <div class="m-form__actions m-form__actions--solid">
                                <button type="submit" class="btn btn-success">Submit</button>
                                <button type="reset" class="btn btn-secondary">Cancel</button>
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
                <!--end::Portlet-->
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")

<script type="text/javascript">
    $.ajax({
        type: "GET",
        url: "@Url.Action("GetRoles", "Admin")",
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        success: function (data) {
            $.each(data, function (index, item) {
                jQuery.grep(item, function(role, i) {
                     $('#roles').append($('<option>', {
                        value: role.ID,
                        text: role.Name
                    }));
                });
            });
        }
    });
</script>